Web style and inteface fixes.
fix: a few more tables weren't using the listingTable style making them look like black bordered ugly things.
fix: a few table messages that belong in th's were in td's.
upd: stat-view looked ugly.
fix: too many buttons for different sections too close together.  Added an open panel to separate them in class-view.
fix: table cells marked with white_space class were turned into block display rather than table-cell display.  fixed in css.

git-svn-id: svn+ssh://buildserver.lin-k.net/scm/svn/products/safe-online/trunk@1495 cd7dd898-ab41-4057-98bc-1513970a52e4

diff --git a/scripts/bashlib b/scripts/bashlib
--- a/scripts/bashlib
+++ b/scripts/bashlib
@@ -213,7 +213,7 @@ emit() {
         local font=$reset$textstyle$textcolor
         text=$font${text//$reset/$font}
         
-        echo -ne "\r$reset $style$color* $text"                      >&$fd
+        echo -n $'\r'"$reset $style$color* $text"                   >&$fd
     fi
 } # _____________________________________________________________________
 
@@ -262,7 +262,7 @@ spinner() {
     local output=0
     unset spinPid
 
-    # Any remaining options are the exit status of an existing spinner.
+    # Any remaining options are the exit status of an existing spinner or spinner type.
     while [[ $1 = -* ]]; do
         arg=${1#-}
         shift
@@ -311,6 +311,9 @@ spinner() {
     trap 'done="${red}failed"; break' USR2
     trap 'break' USR1
 
+    # Toggle screen monitor status.
+    [[ $TERM = screen* ]] && screen -X monitor
+
     # Figure out what FD to use for our messages.
     [[ -t 1 ]]; local fd=$(( $? + 1 ))
 
@@ -327,10 +330,10 @@ spinner() {
     while true; do
         if (( output ))
         then echo -n $'\r'                                          >&$fd
-        else echo -n "$load$eel"                                        >&$fd
+        else echo -n "$load$eel"                                    >&$fd
         fi
 
-        echo -n "$reset $style$color${graphics[i++ % 4]} "      >&$fd
+        echo -n "$reset $style$color${graphics[i++ % 4]} "          >&$fd
 
         if (( output ))
         then echo -n "$reset$bold$blue-$reset "                     >&$fd
@@ -346,6 +349,9 @@ spinner() {
     # Get rid of the spinner traps.
     trap - USR1 USR2; (( monitor )) && set -m
 
+    # Toggle screen monitor status back.
+    [[ $TERM = screen* ]] && screen -X monitor
+
     # Spinner final status.
     if (( output ))
     then echo -n $'\r'; text=                                       >&$fd
@@ -353,6 +359,73 @@ spinner() {
     fi
 
     echo "$eel$reset $style$color* $text${text:+ }$bold$done$font." >&$fd
+} # _____________________________________________________________________
+
+
+
+#  ______________________________________________________________________
+# |__ report ___________________________________________________________|
+#
+#       report [-code] [-e] failure-message [success-message]
+#
+# This is a convenience function for replacement of spinner -code.
+#
+# It checks either the exit code of the previously completed command or
+# the code provided as option to determine whether to display the success
+# or failure message.  It calls spinner -code to complete an actively
+# emitted message if there is one.  The success message is optional.
+#
+#   -[code] The exit code to use.
+#   -e      Exit the script on failure.
+#
+report() {
+
+    # Exit Status of previous command.
+    local code=$?
+    local exit=0
+
+    # Parse the options.
+    while [[ $1 = -* && $2 ]]; do
+        arg=${1#-}
+        shift
+
+        # Stop parsing when arg is --
+        [[ $arg = - ]] && break
+
+        # Process arg: Either a spinner type or result code.
+        if [[ $arg = *[^0-9]* ]]; then
+            case $arg in
+                e) exit=1   ;;
+            esac
+        else code=$arg
+        fi
+    done
+
+    # Initialize the vars.
+    local failure=$1
+    local success=$2
+
+    # Check usage.
+    (( ! $# )) || getArgs -q :h "$@" && {
+        emit -y 'Please specify at least a failure message as argument.'
+        return 1
+    }
+
+    # Proxy call to spinner.
+    (( spinPid )) \
+        && { spinner -$code; }
+ 
+    # Success or failure message.
+    if (( ! code ))
+    then [[ $success ]] && emit     "  $success"
+    else [[ $failure ]] && emit -R  "  $failure"
+    fi
+
+    # Pass on exit code.
+    (( exit )) \
+        && exit   $code \
+        || return $code
+
 } # _____________________________________________________________________
 
 
@@ -688,10 +761,10 @@ showHelp() {
 
     # Print out the help header.
     echo $reset$bold                                                >&$fd
-    echo -e "\t\t$appName"                                          >&$fd
+    echo $'\t\t'"$appName"                                          >&$fd
     echo $reset$green                                               >&$fd
     echo "$appDesc" | fmt -w 70 | sed $'s/^/\t/'                    >&$fd
-    echo -e "\t   $reset$bold~ $reset$yellow$appAuthor"             >&$fd
+    echo $'\t'"   $reset$bold~ $reset$yellow$appAuthor"             >&$fd
     echo $reset                                                     >&$fd
 
     # Print out the application options and columnize them.
@@ -753,11 +826,12 @@ quote() {
 #  ______________________________________________________________________
 # |__ Shorten ___________________________________________________________|
 #
-#       shorten path [prefix]...
+#       shorten [-p pwd] path [prefix]...
 #
 # Shorten an absolute path for pretty printing by cutting
 # off PWD and replacing HOME by ~.
 #
+#   -p      Use the given pathname as the base for relative filenames instead of PWD.
 #   path    The path string to shorten.
 #   prefix  Prefix strings that must be cut off the beginning.
 #           Only the first prefix string matched will be cut off.
@@ -771,14 +845,16 @@ shorten() {
     }
 
     # Parse the options.
-    local prefix
-    local path=$1; shift
+    local prefix path pwd=$PWD
+    [[ $1 = -p ]] && { pwd=$2; shift 2; }
+    path=$1; shift
 
-    # Dot-directories.
+    # Make path absolute, clean out repeated slashes and dot-directories.
+    [[ $path = /* ]] || path=$PWD/$path
     path=$(sed 's,///*,/,g; s,\(^\|/\)\./,\1,g; s,\(^\|/\)[^/]*/\.\./,\1,g' <<< "$path")
 
     # Replace special paths.
-    path=${path/#$PWD\//}
+    path=${path#$pwd/}
     path=${path/#$HOME/'~'}
 
     # Cut off prefix.
@@ -1053,7 +1129,7 @@ hideDebug() {
 stackTrace() {
 
     # Some general debug information.
-    echo -e "\t$bold$BASH$reset v$bold$BASH_VERSION$reset"
+    echo $'\t'"$bold$BASH$reset v$bold$BASH_VERSION$reset"
     #echo "    Was running: $bold$BASH_COMMAND $*$reset"
     echo
     echo "    [Shell    : $bold$(printf %15s "$SHLVL")$reset]    [Subshells : $bold$(printf %5s "$BASH_SUBSHELL")$reset]"
